config/routes.rb
AlugSeguro::Application.routes.draw do
  devise_for :users

  # match 'pages/term' => 'pages#term'
  match 'pages/index' => 'pages#index'

  resources :consoles

  resources :price_ranges

  resources :users

  resources :games

  resources :game_samples do
    member do
      get 'rent'
      put 'rent_money'
      put 'rent_credit'
    end
  end
  
  resources :genders

  resources :histories

  resources :rents do
    member do
      put 'return_game'
      put 'confirm_devolution'
      put 'accept_rent'
    end
    collection do
      get 'admin'
      get 'devolution'
    end
  end

  root to: 'pages#index'

end

app/models/game_sample.rb
class GameSample < ActiveRecord::Base
  belongs_to :devolution
  belongs_to :game
  has_many :rents

  before_save :generate_identifier

	def generate_identifier
		self.identifier = Digest::MD5.hexdigest("#{self.game.id}#{DateTime.now}")
	end	
	def rent_credit user
		return false unless user.shopcredit
		if user.shopcredit >= self.game.price_range.price
			Rent.request_rent self, user, "credits"
			self.available = false
			if self.save
				user.shopcredit -= self.game.price_range.price.to_i
				user.save
			end
		else
			false
		end
	end	
	
	def rent_money user
		Rent.request_rent self, user, "money"
		self.available = false
		self.save
	end
end

app/controllers/game_samples_controller.rb
class GameSamplesController < ApplicationController
	before_filter :authenticate_user!

	def new
		@game_sample = GameSample.new
	end

	def edit
		@game_sample = GameSample.find params[:id]
	end

	def update
		@game_sample = GameSample.find params[:id]
		if @game_sample.update_attributes params[:game_sample]
			redirect_to game_samples_path
		else
			return 'edit'
		end
  	end

	def create
		@game_sample = GameSample.new params[:game_sample]
		@game_sample.available = true
		if @game_sample.save
			redirect_to game_samples_path
		else
			return 'new'
		end
	end

	def index
		@game_samples = GameSample.where available: true
	end

	def destroy
		@game_sample = GameSample.find params[:id]
		@game_sample.destroy
    	redirect_to game_samples_path
  	end

	def rent
		@game_sample = GameSample.find params[:id]
	end

	def rent_money
		@game_sample = GameSample.find params[:id]
		if @game_sample.rent_money current_user
			redirect_to root_url
		else
			render 'rent'
		end
	end

	def rent_credit
		@game_sample = GameSample.find params[:id]
		if @game_sample.rent_credit current_user
			redirect_to root_url
		else
			render 'rent'
		end
	end
	
end

app/views/game_samples/_form.html.erb
<%= form_for @game_sample do |f| %>
	<%= f.label :jogo %>
	<%= f.collection_select :game_id, Game.all, :id, :name %>
	<br/>
	<br/>
	<%= f.submit 'Salvar', :title => 'Salvar' %>
<% end %>

app/views/game_samples/edit.html.erb
<%= render 'form' %>

app/views/game_samples/index.html.erb
<h3><%= "Lista de todos os exemplares disponiveis" %></h3>

<% if current_user.role == "admin" %>
	<%= link_to "Criar novo", new_game_sample_url %>
<% end %>

<% if @game_samples.empty? %>
	<p><b>Não há nenhum exemplar cadastrado no site</b></p>

<% else %>
	<table class="table_game">
		<th>Nome</th>
		<% if current_user.role == "admin" %>
			<th>Identificador</th>
		<% else %>
			<th>Console</th>
			<th>Gênero</th>
			<th>Desembolso</th>
			<th>Preço diário</th>
		<% end %>

		<% @game_samples.each do |game_sample| %> 
			<tr>
				<td><%= game_sample.game.name %></td>
				<% if current_user.role == "admin" %>
					<td><%= game_sample.identifier %></td>
				<% else %>
					<td><%= game_sample.game.console.name if game_sample.game.console %></td>
			    	<td><%= game_sample.game.gender.name if game_sample.game.gender %></td>
			    	<td><%= "R$#{game_sample.game.price_range.price}0" if game_sample.game.price_range %></td>
			    	<td><%= "R$#{game_sample.game.price_range.decrement_value}0" if game_sample.game.price_range %></td>
			    	<% if game_sample.available? %>
						<td><%= link_to "Alugar", rent_game_sample_url(game_sample), method: 'get' %></td>
					<% else %>
			    		<td> Alugado </td>
					<% end %>
				<% end %>
				<td><%= link_to "Editar", edit_game_sample_url(game_sample) %></td>
				<% if game_sample.rents.empty? %>
					<td><%= link_to "Deletar", game_sample, :method => :delete %></td>
				<% end %>
		    </tr>
		<% end %>
	</table>
<% end %>

app/views/game_samples/new.html.erb
<%= render 'form' %>

app/views/game_samples/rent.html.erb
<h3>Aluguel de Jogo</h3>

<p>
Nome: <%= @game_sample.game.name %> </br>
Genero: <%= @game_sample.game.gender.name if @game_sample.game.gender %> </br>
Console: <%= @game_sample.game.console.name if @game_sample.game.console %> </br>
Preço diário: <%= "R$#{@game_sample.game.price_range.decrement_value}0" if @game_sample.game.price_range %>
</p>

<h3> Desembolso </h3>

<%= "R$#{@game_sample.game.price_range.price}0 ou #{@game_sample.game.price_range.price.to_i} ShopCredits"%> </br></br></br>

<%= link_to "Pagar com cartão de crédito", rent_money_game_sample_url(@game_sample), method: 'put' %> </br></br>
<%= link_to "Pagar com shopcredit", rent_credit_game_sample_url(@game_sample), method: 'put' %>