config/routes.rb
AlugSeguro::Application.routes.draw do
  devise_for :users

  # match 'pages/term' => 'pages#term'
  match 'pages/index' => 'pages#index'

  resources :consoles

  resources :price_ranges

  resources :users

  resources :games

  resources :game_samples do
    member do
      get 'rent'
      put 'rent_money'
      put 'rent_credit'
    end
  end
  
  resources :genders

  resources :histories

  resources :rents do
    member do
      put 'return_game'
      put 'confirm_devolution'
      put 'accept_rent'
    end
    collection do
      get 'admin'
      get 'devolution'
    end
  end

  root to: 'pages#index'

end

app/models/console.rb
class Console < ActiveRecord::Base
	has_many :games
	
	validates :name, :presence => true, :uniqueness => true
end

app/controllers/consoles_controller.rb
class ConsolesController < ApplicationController
	before_filter :authenticate_user!
	
	def new
		@console = Console.new
	end

	def edit
		@console = Console.find params[:id]
	end

	def update
		@console = Console.find params[:id]
		if @console.update_attributes params[:console]
			redirect_to consoles_path
		else
			return 'edit'
		end
  	end

	def create
		@console = Console.new params[:console]
		if @console.save
			redirect_to consoles_path
		else
			return 'new'
		end
	end

	def destroy
		@console = Console.find params[:id]
		@console.destroy
    	redirect_to consoles_path
  	end

	def show
		@console = Console.find params[:id]
		@games = Game.where console_id: params[:id]
	end

	def index
		@consoles = Console.all
	end
	
end

app/views/consoles/_form.html.erb
<%= form_for @console do |f| %>
	<%= f.label :nome %>
	<%= f.text_field :name %>
	<br/>
	<br/>
	<%= f.submit 'Salvar', :title => 'Salvar' %>
<% end %>

app/views/consoles/edit.html.erb
<%= render 'form' %>

app/views/consoles/index.html.erb
<h3><%= "Lista de todos os consoles" %></h3>

<% if current_user.role == "admin" %>
	<%= link_to "Criar novo", new_console_url %>
<% end %>

<% if @consoles.empty? %>
	<p><b>Não há nenhum console cadastrado no site</b></p>

<% else %>
	<table class="table_game">
		<th>Nome</th>

		<% @consoles.each do |console| %> 
			<tr>
				<td><%= console.name %></td>
				<% if current_user.role == "admin" %>
					<td><%= link_to "Editar", edit_console_url(console) %></td>
					<% if console.games.empty? %>
						<td><%= link_to "Deletar", console, :method => :delete %></td>
					<% end %>
				<% end %>
		    </tr>
		<% end %>
	</table>



<% end %>

app/views/consoles/new.html.erb
<%= render 'form' %>

app/views/consoles/show.html.erb
<h3><%= "Lista de Jogos do #{@console.name}" %></h3>

<% if @games.empty? %>
	<p><b>Não há nenhum jogo cadastrado no site</b></p>

<% else %>
	<table class="table_game">
		<th>Nome</th>
		<th>Gênero</th>
		<th>Desembolso</th>

		<% @games.each do |game| %>
			<% game.game_samples.each do |game_sample| %>
				<tr>
					<td><%= game.name %></td>
			    	<td><%= game.gender.name if game.gender %></td>
			    	<td><%= "R$#{game.price_range.price}0" if game.price_range %></td>
			    	<% if game_sample.available? %>
			    		<td><%= link_to "Alugar", rent_game_sample_url(game_sample), method: 'get' %></td>
			    	<% else %>
			    		<td> Alugado </td>
			    	<% end %>
			    </tr>
		    <% end %>
		<% end %>
	</table>
<% end %>