config/routes.rb
AlugSeguro::Application.routes.draw do
  devise_for :users

  # match 'pages/term' => 'pages#term'
  match 'pages/index' => 'pages#index'

  resources :consoles

  resources :price_ranges

  resources :users

  resources :games

  resources :game_samples do
    member do
      get 'rent'
      put 'rent_money'
      put 'rent_credit'
    end
  end
  
  resources :genders

  resources :histories

  resources :rents do
    member do
      put 'return_game'
      put 'confirm_devolution'
      put 'accept_rent'
    end
    collection do
      get 'admin'
      get 'devolution'
    end
  end

  root to: 'pages#index'

end

app/models/rent.rb
class Rent < ActiveRecord::Base
	belongs_to :game_sample
	belongs_to :user
	has_many :payments
	has_one :devolution
	has_one :deliverer
	has_one :history

	validates :initial_value, :presence => true

	def self.request_rent game_sample, user, currency
		rent = Rent.create initial_value: game_sample.game.price_range.price, decrement_value: game_sample.game.price_range.decrement_value, game_sample_id: game_sample.id, user_id: user.id
		History.create date: DateTime.now, value: game_sample.game.price_range.price, transaction_type: "Debt", message: "aluguel", currency: currency, rent_id: rent.id, user_id: user.id
		rent
	end

	def accept_rent
		Deliverer.create date: DateTime.now, rent_id: self.id
		self.date = DateTime.now
		self.save
		self
	end

	def request_return user
		Devolution.create rent_id: self.id
		days = Rent.calculate_rent_duration self.date, DateTime.now
		value = Rent.return_exchange days, self
		History.create date: DateTime.now, value: value, transaction_type: "Credit", message: "devolucao", currency: "credits", rent_id: self.id, user_id: user.id
		user.shopcredit = user.shopcredit + value.to_i
		user.save
		self
	end

	def self.return_exchange day_count, rent
		increment = rent.decrement_value
		game_price = rent.initial_value

		value_to_pay = day_count * increment
		exchange_value = game_price - value_to_pay

		if exchange_value < 0
			exchange_value = 0
		end

		exchange_value
		
	end

	def self.calculate_rent_duration start_date, end_date
		days = ((end_date.to_i - start_date.to_i) / 3600 / 24) + 1

		if days < 0
			days = 0
		end
		
		days
	end

end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
	before_filter :authenticate_user!

	def index
		current_user_id = current_user.id
		@rents = Rent.where{(user_id == current_user_id) & (date != nil)}
	end

	def return_game
		@rent = Rent.find params[:id]
		@rent.request_return current_user
		redirect_to rents_url
	end

	def admin
		if current_user.role == "admin"
			@rents = Rent.where{date == nil}
		end
	end

	def devolution
		if current_user.role == "admin"
			@devolutions = Devolution.where{date == nil}
		end
	end

	def accept_rent
		@rent = Rent.find params[:id]
		@rent.accept_rent
		redirect_to admin_rents_url
	end

	def confirm_devolution
		@rent = Rent.find params[:id]
		@devolution = @rent.devolution
		@devolution.confirm_return
		redirect_to devolution_rents_url
	end
	
end

app/views/rents/admin.html.erb
<h3><%= "Lista dos alugueis pendentes" %></h3>

<% if @rents.empty? %>
	<p><b>Nenhum aluguel pendente.</b></p>

<% else %>
	<table class="table_game">
		<th>Jogo</th>
		<th>Requisitado em</th>
		<th>Endereco</th>

		<% @rents.each do |rent| %> 
			<tr>
				<td><%= rent.game_sample.game.name %></td>
				<td><%= rent.created_at.strftime("%m/%d/%Y") %></td>
				<td><%= "#{rent.user.street} - #{rent.user.city}/#{rent.user.state}" %></td>
				<td><%= link_to "Enviar jogo", accept_rent_rent_url(rent), method: 'put'%></td>
		    </tr>
		<% end %>
	</table>
<% end %>

app/views/rents/devolution.html.erb
<h3><%= "Lista das devolucoes pendentes" %></h3>

<% if @devolutions.empty? %>
	<p><b>Nenhuma devolucao pendente.</b></p>

<% else %>
	<table class="table_game">
		<th>Jogo</th>
		<th>Requisitado em</th>
		<th>Endereco</th>

		<% @devolutions.each do |devolution| %> 
			<tr>
				<td><%= devolution.rent.game_sample.game.name %></td>
				<td><%= devolution.created_at.strftime("%m/%d/%Y") %></td>
				<td><%= "#{devolution.rent.user.street} - #{devolution.rent.user.city}/#{devolution.rent.user.state}" %></td>
				<td><%= link_to "Buscar jogo", confirm_devolution_rent_url(devolution.rent_id), method: 'put'%></td>
		    </tr>
		<% end %>
	</table>
<% end %>

app/views/rents/index.html.erb
<h3><%= "Lista dos meus alugueis" %></h3>

<% if @rents.empty? %>
	<p><b>Voce nunca alugou um jogo.</b></p>

<% else %>
	<table class="table_game">
		<th>Jogo</th>
		<th>Alugado em</th>
		<th>Devolvido?</th>
		<th>Devolução</th>
		<th>A receber</th>

		<% @rents.each do |rent| %> 
			<tr>
				<td><%= rent.game_sample.game.name %></td>
				<td><%= rent.date.strftime("%m/%d/%Y") %></td>
				<% if rent.devolution %>
					<td>Sim</td>
				<% else %>
					<td>Nao</td>
					<td><%= link_to "Devolver", return_game_rent_url(rent), method: 'put'%></td>
				<% end %>
				<% unless rent.devolution %>
					<% 
						days = Rent.calculate_rent_duration rent.date, DateTime.now
						value = Rent.return_exchange days, rent
					%>
					<td><%= "R$#{value}0" %></td>
				<% end %>
		    </tr>
		<% end %>
	</table>
<% end %>