config/routes.rb
AlugSeguro::Application.routes.draw do
  devise_for :users

  # match 'pages/term' => 'pages#term'
  match 'pages/index' => 'pages#index'

  resources :consoles

  resources :price_ranges

  resources :users

  resources :games

  resources :game_samples do
    member do
      get 'rent'
      put 'rent_money'
      put 'rent_credit'
    end
  end
  
  resources :genders

  resources :histories

  resources :rents do
    member do
      put 'return_game'
      put 'confirm_devolution'
      put 'accept_rent'
    end
    collection do
      get 'admin'
      get 'devolution'
    end
  end

  root to: 'pages#index'

end

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html>
<head>
  <title>AlugSeguro</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div id="header">
		<div id="left_header">
			<!-- <%= link_to image_tag("logotipo.png"), root_url %> -->
		</div>
		<div id="right_header">
			<% if user_signed_in? %>
          <% if current_user.role == "admin" %>
            <h3> <%="Seja bem vindo novamente, #{current_user.name}." %>
          <% else %>
            <h3> <%="Olá, #{current_user.name}. Você possui #{current_user.shopcredit.to_i} ShopCredits" %>
          <% end %>
          <%= link_to "Sair", destroy_user_session_url, method: :delete %> </h3>
      <% else %>
          <h3>Seja bem vindo! <%= link_to 'Faca seu login', new_user_session_path %></h3>
      <% end %>
      <h3><%= DateTime.now.strftime("Data: %d/%m/%Y") %></h3>
		</div>
	</div>
	
  <div id="menu">
		<ul>
      <% if user_signed_in? %>
        <% if current_user.role == "admin" %>
          <li><%= link_to "Consoles", consoles_url %></li>
          <li><%= link_to "Generos", genders_url %></li>
          <li><%= link_to "Preços", price_ranges_url %></li>
          <li><%= link_to "Jogos", games_url %></li>
          <li><%= link_to "Exemplares", game_samples_url %></li>

        <% else %>
          <li><%= link_to 'Home', root_url %></li>
          <li><%= link_to 'Jogos', games_path %></li>
          <li><%= link_to 'Generos', genders_path %></li>
          <li><%= link_to 'Meus Alugueis', rents_path %></li>
          <li><%= link_to 'Historico', histories_path %></li>
        <% end %>

      <% else %>
        <li><%= link_to 'Home', root_url %></li>
        <li><%= link_to 'Cadastrar', new_user_url %></li>
      <% end %>
		</ul>
	</div>

  <div id="content">
    <div id="central_content">
      <% if user_signed_in? %>
        <div id="top_central_content">
              <ul>
                <% if current_user.role == "admin" %>
                  <li><%= link_to "Aluguéis (#{Rent.where{date == nil}.count})", admin_rents_url %></li>
                  <li><%= link_to "Devoluções (#{Devolution.where{date == nil}.count})", devolution_rents_url %></li>
                <% else %>
                <!-- <li><%= link_to "Perfil", current_user %></li> -->
                  <% Console.all.each do |console| %>
                    <li><%= link_to console.name,  console %></li>
                  <% end %>
                <!-- <li><%= link_to "Sair", destroy_user_session_url, method: :delete %></li> -->
                <% end %>
              </ul>
        </div>
      <% else %>

      <% end %>
      <div id="middle_central_content">
        <%= yield %>
      </div>  
    </div>
  </div>
  <!-- <div id="footer">
		<h4>Todos os Direitos Reservados</h4>
	</div> -->
</body>
</html>